// Generated by https://quicktype.io

export interface GitResponse {
  status:  number;
  url:     string;
  headers: { [key: string]: string };
  data:    data[];
}

export interface data {
  sha:          string;
  node_id:      string;
  commit:       Commit;
  url:          string;
  html_url:     string;
  comments_url: string;
  author:       Author;
  committer:    Author;
  parents:      Parent[];
}

export interface Author {
  login:               string;
  id:                  number;
  node_id:             string;
  avatar_url:          string;
  gravatar_id:         string;
  url:                 string;
  html_url:            string;
  followers_url:       string;
  following_url:       string;
  gists_url:           string;
  starred_url:         string;
  subscriptions_url:   string;
  organizations_url:   string;
  repos_url:           string;
  events_url:          string;
  received_events_url: string;
  type:                string;
  site_admin:          boolean;
}

export interface Commit {
  author:        CommitAuthor;
  committer:     CommitAuthor;
  message:       string;
  tree:          Tree;
  url:           string;
  comment_count: number;
  verification:  Verification;
}

export interface CommitAuthor {
  name:  string;
  email: string;
  date:  string;
}


export interface Tree {
  sha: string;
  url: string;
}

export interface Verification {
  verified:  boolean;
  reason:    string;
  signature: null | string;
  payload:   null | string;
}

export interface Parent {
  sha:      string;
  url:      string;
  html_url: string;
}
// Generated by https://quicktype.io

export interface APIReponse {
  sucess: boolean;
  principal_url: string;
  data: CommitsReponse[]
}

export interface CommitsReponse {
  name:    string;
  avatar:  string;
  mail:    string;
  commit:  string;
  url:     string;
  created: string;
}

// Generated by https://quicktype.io

export interface RepoList {
  id:          number;
  name:        string;
  description: string;
  html_ulr:    string;
  language:    string;
  visibility:  string;
  owner:       string;
}

